# Generated by Django 4.1.7 on 2023-06-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_experience', models.FloatField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
